### ISSUE TITLE
Add Contributors

### ISSUE THREAD

**Issue by MoonieGZ** [axsLeaf/FelicityOne#5]
@all-contributors please add @axsLeaf for code and financial

**Comment by axsLeaf** [comment]
@all-contributors add @hussainq for doc and example

**Comment by axsLeaf** [comment]
@all-contributors add @TheLastJoaquin for data

**Comment by axsLeaf** [comment]
@all-contributors add @Subhaven for design

**Comment by MoonieGZ** [comment]
@all-contributors add @quiffboy for financial

**Comment by MoonieGZ** [comment]
@all-contributors add @gothfemme for tool and mentoring

**Comment by MoonieGZ** [comment]
bot pls

**Comment by MoonieGZ** [comment]
@all-contributors add @gothfemme for tool and mentoring

**Comment by MoonieGZ** [comment]
@all-contributors add @camohiddendj for financial and infra
